name: 1. 建立 Release

on:
  push:
    tags:
      - 'm*'
      - 'l*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  create-release:
    name: 建立 Release
    runs-on: ubuntu-latest
    steps:
      - name: 建立 Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}