name: 1. 建立 Release（僅建立，不上傳檔案）

on:
  push:
    tags:
      - 'm*'
      - 'l*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  create-release:
    name: 建立 Release
    runs-on: ubuntu-latest
    steps:
      - name: 建立 Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 取得 Release 資訊
        id: get_release
        uses: actions/github-script@v7
        with:
          script: |
            const release = await github.rest.repos.getReleaseByTag({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag: context.ref.replace('refs/tags/', '')
            });
            return release.data.upload_url;
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 列印 upload_url
        run: echo "${{ steps.get_release.outputs }}"
